[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':(exclude)_!nbox/' ':(exclude)_writing/' ':(exclude)_drafts/' ':(exclude)_work/' ':(exclude)_farm/' ':(exclude)_life/' ':(exclude)_plan/' ':(exclude)story-engine/'"

[[redirects]]
  from = "https://douglangille.netlify.app/*"
  to = "https://douglangille.ca/:splat"
  status = 301
  force = true  

[[redirects]] 
  from = "https://www.douglangille.ca/*"
  to = "https://douglangille.ca/:splat"
  status = 301
  force = true
