[[redirects]]
  from = "https://douglangille.netlify.app/*"
  to = "https://douglangille.ca/:splat"
  status = 301
  force = true  
  
  from = "https://www.douglangille.netlify.app/*"
  to = "https://www.douglangille.ca/:splat"
  status = 301
  force = true